### ISSUE TITLE
Test failures in SharedFileWriterTest on Linux systems

### ISSUE THREAD

**Issue by jotomo** [pmwmedia/tinylog#16] opened 2015-12-13 16:02 UTC
Running _SharedFileWriterTest_ on Linux I get test failures as described here: https://github.com/jotomo/tinylog/commit/0b41014894d5986d163e266411d993abaa1ca9ee, indicating a problem when writing to a log file concurrently.
@pmwmedia I'm assuming you're running Windows. TravisCI would run the tests on Linux - I've seen you tested TravisCI but dropped it again. Remember why?

Updated: running a Linux system natively, or a Linux VM on a Linux hosts, there are intermittend build failures in tests that inherit from _AbstractTimeBasedPolicy_ (mostly in _WeeklyPolicyTest_). These failures occur 1-3 times out of 10 on an Arch Linux system (as December 2015). It seems that the _SystemTimeMock_ is not thread-safe and occassionally returns the actual system time, leading to test failures.

**Comment by pmwmedia** [comment] 2015-12-13 17:17
I dropped TravisCI, because I haven't any Linux machine for developing. Setting up a Linux machine and activating Travis CI is on the task list for tinylog 2. Because of the reported test failures, I will do it before releasing tinylog 1.1. I want to be sure that shared file writer will work.

**Comment by pmwmedia** [comment] 2015-12-14 21:37
All tests are running on my Ubuntu virtual machine as well as on Travis CI now. Can you confirm that the bug is fixed?

**Comment by jotomo** [comment] 2015-12-14 22:11
Testing the v1.1 branch, I got around 5 clean runs and then a failure (using _ant test_)
```
    [junit] Testcase: testFailedFlushWriter took 0.026 sec
    [junit] Testcase: testFlush took 0.003 sec
    [junit] 	FAILED
    [junit] expected:<1> but was:<2>
    [junit] junit.framework.AssertionFailedError: expected:<1> but was:<2>
    [junit] 	at org.pmw.tinylog.WritingThreadTest.testFlush(WritingThreadTest.java:102)
    [junit] 
```
Running _mvn clean test_ against v2.0, about every third run fails one of these:
```
testFromProperties(org.pmw.tinylog.policies.WeeklyPolicyTest)  Time elapsed: 0.076 sec  <<< FAILURE!
java.lang.AssertionError
	at org.pmw.tinylog.policies.WeeklyPolicyTest.testFromProperties(WeeklyPolicyTest.java:433)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


testFlush(org.pmw.tinylog.WritingThreadTest)  Time elapsed: 0.003 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<2>
	at org.pmw.tinylog.WritingThreadTest.testFlush(WritingThreadTest.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```
I'll try to figure out what's going in the next couple of days.

**Comment by jotomo** [comment] 2015-12-16 10:51
Failure in _WritingThreadTest.teshFlush:102:_ the test logs two entities via the first writer. It seems to me as if occassionally the thread manages to flush after each one of those, and thus flushing twice rather than just once. Which seems harmless. Changing the assert to accept >= 1 as a valid number of flushes seems fine to me.

Failures in _WeeklyPolicyTest_: all evolve around _System.currentTimeMillis_. The value is system-dependant but that doesn't seem to be an issue.
Checking the failing test (WeeklyPolicyTest.java:433) and checking the called _policy.check(String)_ method, which evaulates _System.currentTimeMillis() < nextTime_. The values - when the test fails are: _current_: 86400000, _next_: 1450396800000. _next_ is peculiar, because that's about now in real time, rather than what the _System_ mock is set to (the beginning of Unix-Time plus one day).
I've traced the cause to _org.pmw.tinylog.policies.WeeklyPolicy#createCalendar(int)_, which in turn calls _java.util.Calendar#getInstance()_ which ends up calling _sun.util.locale.provider.CalendarProviderImpl#getInstance_ and this method calls _System.currentTimeMills_() and fetches the **real** system time because the System mock is not active here. Why this only leads to a failure in every 3-5 or so runs eludes me still though ...

So, these failures seem to be about robustness issues in the test code, rather than bugs in the production code.

**Comment by pmwmedia** [comment] 2015-12-16 22:34
*WritingThreadTest.teshFlush*: One **as well as** two flushes are acceptable for the first writer. Nevertheless I'm surprised that you get two flushes for the first writer reproducibly. This case should be happen very, very rarely.

*WeeklyPolicyTest*: In this case *Calendar* should be mocked in *AbstractTimeBasedPolicyTest*.

**Comment by pmwmedia** [comment] 2015-12-22 18:24
I have fixed ````WritingThreadTest```` in commit ff281c7b8dbc8e50e5734a1f2fca4d70275339e5. Failures in ````WeeklyPolicyTest````` are still not reproducible neither on my PC nor in my Linux VM. 

@jotomo Which Linux distribution are you using? Do you use the Oracle JDK or OpenJDK? Which version do you have?

**Comment by jotomo** [comment] 2015-12-22 19:30
@pmwmedia I'm using Arch Linux with OpenJDK 1.8u66.
I can reproduce this error using VirtualBox to run Antergos[1] (Arch Linux-based distribution with GUI installer; pretty close to what I'm running) and running in a terminal:
```
sudo pacman -S jdk8-openjdk git maven
git clone https://github.com/pmwmedia/tinylog.git
cd tinylog
for i in `seq 1 20`; do mvn test || break;done
```
The error seems to occur less often in a VM, but does so within 10 iterations. System specs are similar to yours (i7-4770, 16 GB RAM, SSD).
I've installed Antergos in the VM, but it should also work in Live-mode.

I didn't get around to testing this more so far ...  let me know if I can you need help with Linux.

[1] https://antergos.com/try-it/

**Comment by jotomo** [comment] 2015-12-22 20:13
@pmwmedia ... though I wouldn't know why the issue should be specific to Arch, but should occur on e.g. Ubuntu/Debian too. 
I'll let it run with the Oracle JDK, see if that has an impact.

**Comment by jotomo** [comment] 2015-12-22 22:00
@pmwmedia Nope, JDK doesn't seem to make a difference, Oracle JDK failed on build 1 and 11, so pretty much the same as with OpenJDK.
I let Travis run the build 10 times to see if that produces the error, but it didn't, instead it produced a new intermittent failure ... https://travis-ci.org/jotomo/tinylog/builds/98401781#L1960

**Comment by pmwmedia** [comment] 2015-12-23 12:19
@jotomo Thanks for testing and providing specific information about your environment. I have increased the sleeping time to make the test more robust. A cleaner rewrite of these test without any fixed sleeping will follow after the release of tinylog 1.1. At http://koding.com, I could successfully execute:
```
git clone https://github.com/pmwmedia/tinylog.git
cd tinylog
for i in `seq 1 20`; do mvn test || break;done
```
I had hoped to be able to reproduce the failing of ````WeeklyPolicyTest```` there. But all 20 runs were successful. The next step will be to set up Antergos Linux. Hopefully I will be able to reproduce the problems with ````WeeklyPolicyTest```` there.

**Comment by jotomo** [comment] 2015-12-23 14:16
@pmwmedia The Koding VM uses a _single_ CPU core. I have 2 cores assigned to my VM (along with 2 GB of RAM). If it's a threading issues this might have an impact on it. Note that VirtualBox by default assign a single core when creating a new VM (if you're running your VM on VirtualBox).

**Comment by jotomo** [comment] 2015-12-23 16:14
@pmwmedia I've set up a Ubuntu 14.0.4 VM. With a single core, I get 100 clean runs. With two cores 2 get a failure after 38 runs.

**Comment by jotomo** [comment] 2015-12-23 17:14
@pmwmedia Same with my Antergos VM: no failures with a single core, with failures happening when adding another core.

**Comment by pmwmedia** [comment] 2015-12-23 22:32
@jotomo That tests fail only with multiple cores is already a good hint. So it seems to be a concurrency problem with the mocks. I guess that the mocked times are not set in a thread-safe way.

**Comment by pmwmedia** [comment] 2015-12-27 22:15
@jotomo I have set up a Ubuntu 15.10 VM. With two cores, I got three times 100 clean runs. With four cores the same result. I tried even six times.

**Comment by jotomo** [comment] 2015-12-28 11:08
@pmwmedia Okay, so this is then a problem that only manifests itself if Linux is running natively, or the host system is Linux, assuming whatever Windows passes through to the VM behaves differently than running Linux natively. It's unlikely I'll get around to debug this further on my system, my experience with (debugging) threading is limited at the moment, so this would require quiet a bit of time. But, I think we can conclude that this is not a problem in the production code, but a problem with the test system (mock) which is not a problem for Travis, so this is not a pressing concern. I'll put what was learnt into the description of the issue and leave the issue open for now. Sounds good?

**Comment by pmwmedia** [comment] 2016-01-21 21:08
Today the bug appears also on my Windows machine. The problem is inlining by the JVM. This breaks mocking of native methods.
Source: https://virgo47.wordpress.com/2012/06/22/changing-system-time-in-java/

@jotomo Can you confirm that b28eb8487e47e206e5d95e866c2a7d9cedac4801 fixes also the bug on your machine?

**Comment by jotomo** [comment] 2016-01-22 21:14
@pmwmedia I'm having trouble getting the build to fail using a revision just before the inline commit. I can't reproduce it on a VM snapshot from December either, so this must stem from a code change. Checking the commits I noticed an occurrence of _System.currentTimeMillis_ has been removed here: https://github.com/pmwmedia/tinylog/commit/460ab3792b1fba763a503ee28aeeb5275f24e5f6#diff-beff1167fbfce45bfcff9b40f990a98cL68
Reverting that commit and things start to fail nicely reproducable again. Now lets see if disabling inlining fixes it again.

**Comment by jotomo** [comment] 2016-01-22 22:11
With inlining disabled I get 161 clean runs, whereas without inlining I get failures within 30 runs. So I'd call that fixed. The failure I got in the 162th run was:
```
Running org.tinylog.ConfiguratorTest
Tests run: 18, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.652 sec <<< FAILURE! - in org.tinylog.ConfiguratorTest
testWritingThread(org.tinylog.ConfiguratorTest)  Time elapsed: 0.127 sec  <<< FAILURE!
java.lang.AssertionError: expected:<4> but was:<3>
	at org.tinylog.ConfiguratorTest.testWritingThread(ConfiguratorTest.java:683)
```
This is unrelated to the inlining issue, I'd say, and should be a rare issue where at line 682 the sleep for 100ms isn't long enough. Upping that a bit should avoid that rare case too.
I've reset the branch to be up-to-date with master (to drop my revert) and doubled the sleep time and that's running for another 200 times, which I expect to pass - just to be sure.

**Comment by pmwmedia** [comment] 2016-01-22 23:40
Thank you for testing :-) In general, fixed waiting times are not the best. I'm experimenting with other solutions. One of them will be part of the complete rewrite for tinylog 2.0.

**Closed by pmwmedia** 2016-01-22 23:40 UTC
Labels: bug, help wanted
